"""add linked_transaction_id to transaction

Revision ID: 01eaad8c6386
Revises: c5fa00af621c
Create Date: 2026-04-22 20:04:45.271161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01eaad8c6386'
down_revision: Union[str, Sequence[str], None] = 'c5fa00af621c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('linked_transaction_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'transaction', ['linked_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'linked_transaction_id')
    # ### end Alembic commands ###
