"""empty message

Revision ID: 073d3175396d
Revises: 
Create Date: 2026-02-28 16:41:44.900423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '073d3175396d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_value', sa.Float(), nullable=False),
    sa.Column('archived_value', sa.Float(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_position'), 'account', ['position'], unique=False)
    op.create_table('pot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_pot_account_name'),
    sa.UniqueConstraint('account_id', 'position', deferrable=True, initially='DEFERRED', name='uq_pot_account_position')
    )
    op.create_index(op.f('ix_pot_position'), 'pot', ['position'], unique=False)
    op.create_table('sub_pot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prevision', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('pot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pot_id', 'name', name='uq_sub_pot_pot_name'),
    sa.UniqueConstraint('pot_id', 'position', deferrable=True, initially='DEFERRED', name='uq_sub_pot_pot_position')
    )
    op.create_index(op.f('ix_sub_pot_position'), 'sub_pot', ['position'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', name='typetransaction'), nullable=False),
    sa.Column('motif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurrent', sa.Boolean(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('DAY', 'WEEK', 'MONTH', name='typerecurrence'), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('recurrence_day', sa.Integer(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_pot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sub_pot_id'], ['sub_pot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_sub_pot_position'), table_name='sub_pot')
    op.drop_table('sub_pot')
    op.drop_index(op.f('ix_pot_position'), table_name='pot')
    op.drop_table('pot')
    op.drop_index(op.f('ix_account_position'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
