"""add subpot_snapshot

Revision ID: 6ab6cbb261b3
Revises: 01eaad8c6386
Create Date: 2026-04-22 20:28:24.763658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab6cbb261b3'
down_revision: Union[str, Sequence[str], None] = '01eaad8c6386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subpotsnapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sub_pot_id', sa.String(), nullable=False),
    sa.Column('pot_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('prevision', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], ),
    sa.ForeignKeyConstraint(['sub_pot_id'], ['sub_pot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_pot_id', 'year', 'month', name='uq_subpot_snapshot')
    )
    op.create_index(op.f('ix_subpotsnapshot_account_id'), 'subpotsnapshot', ['account_id'], unique=False)
    op.create_index(op.f('ix_subpotsnapshot_pot_id'), 'subpotsnapshot', ['pot_id'], unique=False)
    op.create_index(op.f('ix_subpotsnapshot_sub_pot_id'), 'subpotsnapshot', ['sub_pot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subpotsnapshot_sub_pot_id'), table_name='subpotsnapshot')
    op.drop_index(op.f('ix_subpotsnapshot_pot_id'), table_name='subpotsnapshot')
    op.drop_index(op.f('ix_subpotsnapshot_account_id'), table_name='subpotsnapshot')
    op.drop_table('subpotsnapshot')
    # ### end Alembic commands ###
