"""ajout archived_value dans compte

Revision ID: 7918f684b35a
Revises: c692f31d2c3e
Create Date: 2026-02-03 16:27:27.830015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7918f684b35a'
down_revision: Union[str, Sequence[str], None] = 'c692f31d2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compte', sa.Column('archived_value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compte', 'archived_value')
    # ### end Alembic commands ###
