"""add_user_settings_currency

Revision ID: 7fcc7863ff2a
Revises: 073d3175396d
Create Date: 2026-04-10 06:10:50.089411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fcc7863ff2a'
down_revision: Union[str, Sequence[str], None] = '073d3175396d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GBP', 'CHF', 'JPY', 'CAD', 'AUD', name='currency'), server_default='EUR', nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersettings')
    # ### end Alembic commands ###
