"""contrainte unicite pot souspot

Revision ID: 89871eafcceb
Revises: 7918f684b35a
Create Date: 2026-02-09 14:57:10.627221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89871eafcceb'
down_revision: Union[str, Sequence[str], None] = '7918f684b35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pot_compte_name', 'pot', ['compte_id', 'name'])
    op.create_unique_constraint('uq_sous_pot_pot_name', 'sous_pot', ['pot_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sous_pot_pot_name', 'sous_pot', type_='unique')
    op.drop_constraint('uq_pot_compte_name', 'pot', type_='unique')
    # ### end Alembic commands ###
