"""ajout des contraintes sur la position deferred

Revision ID: 8f3198eda358
Revises: fc239760187d
Create Date: 2026-02-13 20:56:29.201267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3198eda358'
down_revision: Union[str, Sequence[str], None] = 'fc239760187d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pot_compte_position', 'pot', ['compte_id', 'position'], deferrable=True, initially='DEFERRED')
    op.create_unique_constraint('uq_sous_pot_pot_position', 'sous_pot', ['pot_id', 'position'], deferrable=True, initially='DEFERRED')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sous_pot_pot_position', 'sous_pot', type_='unique')
    op.drop_constraint('uq_pot_compte_position', 'pot', type_='unique')
    # ### end Alembic commands ###
