"""add recurrence_day and change typeRecurrence

Revision ID: 92213f4c192f
Revises: fadad4cacc8a
Create Date: 2026-02-21 15:30:58.042247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92213f4c192f'
down_revision: Union[str, Sequence[str], None] = 'fadad4cacc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('recurrence_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'recurrence_day')
    # ### end Alembic commands ###
