"""add_portfolio_snapshot

Revision ID: c5fa00af621c
Revises: f488089a6267
Create Date: 2026-04-17 09:01:40.505919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5fa00af621c'
down_revision: Union[str, Sequence[str], None] = 'f488089a6267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfoliosnapshot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', name='uq_portfolio_snapshot_account_date')
    )
    op.create_index(op.f('ix_portfoliosnapshot_account_id'), 'portfoliosnapshot', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfoliosnapshot_snapshot_date'), 'portfoliosnapshot', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfoliosnapshot_snapshot_date'), table_name='portfoliosnapshot')
    op.drop_index(op.f('ix_portfoliosnapshot_account_id'), table_name='portfoliosnapshot')
    op.drop_table('portfoliosnapshot')
    # ### end Alembic commands ###
