"""add is_processed to transaction

Revision ID: fadad4cacc8a
Revises: 8f3198eda358
Create Date: 2026-02-21 15:08:29.548305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadad4cacc8a'
down_revision: Union[str, Sequence[str], None] = '8f3198eda358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'is_processed')
    # ### end Alembic commands ###
