"""mise en place de la position

Revision ID: fc239760187d
Revises: 89871eafcceb
Create Date: 2026-02-10 13:37:26.459782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc239760187d'
down_revision: Union[str, Sequence[str], None] = '89871eafcceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compte', sa.Column('position', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_compte_position'), 'compte', ['position'], unique=False)
    op.add_column('pot', sa.Column('position', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_pot_position'), 'pot', ['position'], unique=False)
    op.add_column('sous_pot', sa.Column('position', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sous_pot_position'), 'sous_pot', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sous_pot_position'), table_name='sous_pot')
    op.drop_column('sous_pot', 'position')
    op.drop_index(op.f('ix_pot_position'), table_name='pot')
    op.drop_column('pot', 'position')
    op.drop_index(op.f('ix_compte_position'), table_name='compte')
    op.drop_column('compte', 'position')
    # ### end Alembic commands ###
